#!/usr/bin/env ruby
#^syntax detection
source 'https://supermarket.getchef.com'

cookbook 'yum', '2.4.4'
cookbook 'mysql'
cookbook 'php'
cookbook 'redisio'
cookbook 'memcached'
cookbook 'nginx', '2.0.8' # Latest to support yum 2.x cookbook
cookbook 'apache2'
cookbook 'elasticsearch'
cookbook 'jetty', :github => 'inviqa/chef-jetty'
cookbook 'solr', :github => 'inviqa/chef-solr'
cookbook 'chef-varnish', :github => 'inviqa/chef-varnish'
cookbook 'config-driven-helper', :github => 'inviqa/chef-config-driven-helper'


# cookbook 'docker', '0.22.0' # Latest to support yum 2.x cookbook
# cookbook 'docker-permissions', :path => './site-cookbooks/docker-permissions'
# cookbook 'runit', '1.4.0' # Latest to support yum 2.x cookbook
# cookbook 'knife-container', :path => './site-cookbooks/knife-container'
