#!/usr/bin/env ruby
# ^ Syntax hint

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Network configuration - never actually used for the docker containers but
  # specified to be the same as the docker host VM so hosts updater will work
  config.vm.network :private_network, ip: "10.143.137.214"
  config.ssh.forward_agent = true

  # vagrant-hostsupdater settings
  config.vm.hostname = "docker-based-dev-environment.dev"
  # config.hostsupdater.aliases = []

  # vagrant-cachier settings
  config.cache.auto_detect = true

  config.vm.synced_folder(
    "../../",
    "/vagrant"
  )

  config.vm.provider "docker" do |d|
      # Set to false if you want local docker instances running
      # For this to work, you need to be on linux.
      # Also, please install both 
      # docker: http://docker.io/
      # knife-container: http://docs.getchef.com/containers.html
      # d.force_host_vm = true  
      d.vagrant_vagrantfile = "./docker/Vagrantfile-dockerhost"
  end

  config.vm.define "base" do |base|
    base.vm.provider "docker" do |d|
      d.build_dir = "../docker/base/"
      d.build_args = ["--tag=inviqa/base"]
      d.name = "base"
      d.remains_running = false
    end
  end

  config.vm.define "web" do |web|
    web.vm.hostname = "docker-web.dev"

    web.vm.synced_folder(
      "./logs",
      "/var/log/"
    )

    web.vm.provider "docker" do |d|
      d.build_dir = "../docker/web/"
      d.name = "web"
      d.ports = ["80:80"]
      # d.volumes = ["logs:/var/log/"]
    end
  end

  config.vm.define "db" do |db|
    db.vm.synced_folder(
      "./logs",
      "/var/log/"
    )

    db.vm.synced_folder(
      "./data/mysql",
      "/var/lib/mysql/"
    )

    db.vm.provider "docker" do |d|
      d.build_dir = "../docker/db/"
      d.name = "db"
      d.ports = ["3306:3306"]
    end
  end

  config.vm.define "redis" do |redis|
    redis.vm.synced_folder(
      "./logs",
      "/var/log/"
    )

    redis.vm.synced_folder(
      "./data/redis",
      "/var/lib/redis"
    )

    redis.vm.provider "docker" do |d|
      d.build_dir = "../docker/redis/"
      d.name = "redis"
      d.ports = ["6739:6739"]
    end
  end
end
